### PR TITLE
Allow doc extensions to override model's default attributes

### PR DESCRIPTION
**Pull request by hygt**
See https://softwaremill.community/t/explicit-explode-true-in-the-generated-openapi/280/3

### CODE REVIEW

**Comment by adamw** [comment]
Seems there are some test failures

**Comment by hygt** [comment]
My bad, I didn't bother trying to deserialize the JSON.
That is super weird, I don't see anything wrong, it's valid OpenAPI.
I'll look into it.

**Comment by hygt** [comment]
OK @adamw I think I figured it out, the decoder was expecting `examples` and `content` fields and I believe that's a bug, see https://github.com/softwaremill/sttp-apispec/pull/113/files#diff-7eda956eb25bc05a87ae9d4bd8db486f99ba1621bc11037d83a8cf5604eb8100R90-R98

**Comment by adamw** [comment]
Yes I think this looks good, thanks :)

**Pull request merged**
